### PR TITLE
Add Compile scripts for libs

### PR DESCRIPTION
**Pull request by 6543**
just some idears/thoughts for #45 and #5

### CODE REVIEW

**Comment by 6543** [comment]
@Gedsh would be nice if you reveal me how you compile the localy :)

PS: you have write access to my fork if you accept the [infitation](https://github.com/6543-forks/InviZible/invitations) (just in case it is usefull ...)

**Comment by Gedsh** [comment]
> would be nice if you reveal me how you compile the localy :)

You can build Golang binaries (dnscrypt, obfs4proxy, snowflake) for android as shown below. Go compiler and Android NDK required. I am using dnscrypt as an example.

#armv7a:

$env:GOPATH=c:\Go\bin\go.exe
$env:GOOS='android'
$env:GOARCH='arm'
$NDK="C:\Users\Alexander\AppData\Local\Android\Sdk\ndk-bundle"
$env:Path += ";$NDK/toolchains/llvm/prebuilt/windows-x86_64/bin"
$env:CCX="$NDK/toolchains/llvm/prebuilt/windows-x86_64/bin/armv7a-linux-androideabi16-clang++"
$env:CC="$NDK/toolchains/llvm/prebuilt/windows-x86_64/bin/armv7a-linux-androideabi16-clang"
$env:CGO_ENABLED=1

#arm64:

$env:GOPATH=c:\Go\bin\go.exe
$env:GOOS='android'
$env:GOARCH='arm64'
$NDK="C:\Users\Alexander\AppData\Local\Android\Sdk\ndk-bundle"
$env:Path += ";$NDK/toolchains/llvm/prebuilt/windows-x86_64/bin"
$env:CCX="$NDK/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android29-clang++"
$env:CC="$NDK/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android29-clang"
$env:CGO_ENABLED=1

#common:

cd C:\Go\My\dnscrypt-proxy-2.0.44\dnscrypt-proxy
go clean
go build -ldflags="-s -w" -o $env:GOPATH/android/dnscrypt-proxy

**Comment by Gedsh** [comment]
To build Purple I2P Android NDK is required. I use android-ndk-r14b for this.

Change the path to libraries in this file https://github.com/PurpleI2P/i2pd/blob/openssl/android_binary_only/jni/Application.mk
I am using PowerShell.

cd C:\Users\Alexander\AppData\Local\Android\Sdk\ndk\android-ndk-r14b
"ndk-build -C C:\i2pd-opensslv2.33.0\android_binary_only -j" | cmd

**Comment by Gedsh** [comment]
> you have write access to my fork if you accept the infitation (just in case it is usefull ...)

Thank you. But unfortunately I have no experience with compile scripts.

**Comment by 6543** [comment]
ok now https://github.com/PurpleI2P/i2pd and https://github.com/guardianproject/gpmaven/tree/master/org/torproject/tor-android-binary are missing only ...

go libs can now be compiled automaticaly by this scritp :) 

wip ...

**Comment by Gedsh** [comment]
> ok now https://github.com/PurpleI2P/i2pd and https://github.com/guardianproject/gpmaven/tree/master/org/torproject/tor-android-binary are missing only ...

Tor for Android https://github.com/guardianproject/tor-android

> go libs can now be compiled automaticaly by this scritp :)

Cool!

**Comment by Gedsh** [comment]
Add script for building Tor for Android from source using Gitlab CI / CD https://github.com/Gedsh/Tor-Android-build-script

**Comment by 6543** [comment]
thanks will add it :)

**Comment by Gedsh** [comment]
Added script for building Purple I2P from source using Gitlab CI / CD https://github.com/Gedsh/Purple-I2P-Android-build-script

**Comment by linsui** [comment]
Based on your great work, I manage to build it with f-droid's gitlab CI but there are some problems. I'm not a dev and have little knowledge about Android. Could you please take a look?
[log](https://gitlab.com/linsui/fdroiddata/-/jobs/983533386) 
[apk file](https://gitlab.com/linsui/fdroiddata/-/jobs/983533386/artifacts/download?file_type=archive)
[build.sh](https://github.com/linsui/InviZible/blob/fdroid-stable/tordnscrypt/libs/build.sh) 
[fdroid metadata](https://gitlab.com/linsui/fdroiddata/-/blob/c6017722786dce05d702cc12d09e6aae8b322e49/metadata/pan.alexander.tordnscrypt.stable.yml)
It seems that the dnscrypt and i2pd work but tor can't start. Maybe ithe reason is that due to the space limitation of gitlab ci I didn't install ndk r20 and r20b so everything is build by r21d.
Thanks!

@6543 Are you still working on this? Would you please take some time to complete this pr? Or I can make another one based on this.

@Gedsh I have some questions. Due to my poor knowledge maybe they are stupid.
- How does the version of i2pd specified? I didn't find it.
- `APP_ABI` for tor is `armeabi` while for i2pd is `armeabi-v7a`. Is this intended?
- Would you like to include two arches in F-Droid? Then autoupdate won't work so that a mr is needed when a new version is available.
- tor for android is available in F-Droid's trusted repo. Is it possible to use that?

Thanks!

**Comment by 6543** [comment]
@linsui feel free to use this pull to finish the work, I have no time to finish it at the moment. So If you like tho have it soon you should pick this up and finish it ;)

**Comment by 6543** [comment]
@linsui I have invited you to my fork: https://github.com/6543-forks/InviZible/invitations so feel free to push to this branch or create a new one based on that from your side ...

**Comment by linsui** [comment]
@6543 Thanks!

**Comment by Gedsh** [comment]
> Based on your great work, I manage to build it with f-droid's gitlab CI

Thank you! Cool job!

> Works well on my device.

Great!

> The icon is the beta one, I don't know why.

I thought the beta would be used for f-droid. But with @IzzySoft we decided to use the stable version. I will change the icon.

> How does the version of i2pd specified? I didn't find it.

It just uses the latest changes. You can use for example:
git clone --single-branch --branch 2.35.0 https://github.com/PurpleI2P/i2pd.git

> APP_ABI for tor is armeabi while for i2pd is armeabi-v7a. Is this intended? In i2pd's makefile the APP_ABI is armeabi but in gitlab ci armeabi-v7a is passed. What's the difference?

The difference is in the processor instruction set. Usually modern processors can use armeabi and armeabi-v7a without any problem.
I'm just using build scripts from the Tor and I2P projects with some adaptation. If they listed armabi or armabi-v7a I thought it might be important and just used the same.

> Would you like to include two arches in F-Droid? Then autoupdate won't work so that a mr is needed when a new version is available.

I think it is better to include the armv7a version as it works on both armv7a and arm64 devices.

> tor for android is available in F-Droid's trusted repo. Is it possible to use that?

If you want to. But I will continue to use my own builds as I like using the Tor beta versions in InviZible.

**Comment by linsui** [comment]
> I thought the beta would be used for f-droid. But with @IzzySoft we decided to use the stable version. I will change the icon.

Thanks!

> It just uses the latest changes. You can use for example:
git clone --single-branch --branch 2.35.0 https://github.com/PurpleI2P/i2pd.git

I would prefer to specify a version when build it or it will produce different resultes on every build.

> The difference is in the processor instruction set. Usually modern processors can use armeabi and armeabi-v7a without any problem.
I'm just using build scripts from the Tor and I2P projects with some adaptation. If they listed armabi or armabi-v7a I thought it might be important and just used the same.

I got it!

> I think it is better to include the armv7a version as it works on both armv7a and arm64 devices.

I don't know how the update checker works. @IzzySoft @licaon-kter Could you please help? I got `WARNING: ...pan.alexander.tordnscrypt.stable : Couldn't find package ID` when running the checkupdates.

**Comment by IzzySoft** [comment]
@linsui not my speciality, but: what is the name of your `*.yml` – and what is the packageName in `build.gradle`? The two must match. Work-around for rare cases: if we package it as `pan.alexander.tordnscrypt.stable`, the build/flavor produces it that way, but `build.gradle` has e.g. `pan.alexander.tordnscrypt` (and the suffix is somehow created during the build), there's a matching keyword for the YAML I just saw today (didn't know before it exists): `UpdateCheckName: pan.alexander.tordnscrypt` would tell the updater to check for that packageId, regardless of the "final name". Details in our Metadata Reference: [UpdateCheckName](https://f-droid.org/en/docs/Build_Metadata_Reference/#UpdateCheckName):

> When checking for updates (via `UpdateCheckMode`) this can be used to specify the package name to search for. Useful when apps have a static package name but change it programmatically in some app flavors, by e.g. appending “.open” or “.free” at the end of the package name.

**Comment by linsui** [comment]
@IzzySoft Thanks for your tips! I'll test it. The package name does present in the gradle file.

https://github.com/Gedsh/InviZible/blob/9b8111399dd07bb77b3c7dfdcb1f6567547cc03f/tordnscrypt/build.gradle#L13

**Comment by IzzySoft** [comment]
:man_shrugging: Maybe it complains because there is no `applicationId` in the [`defaultConfig`](https://github.com/Gedsh/InviZible/blob/9b8111399dd07bb77b3c7dfdcb1f6567547cc03f/tordnscrypt/build.gradle#L41)? No idea, I just mentioned what came to mind. I'm not really fit in gradle or Android programming. I can read and understand some things, but that's quite limited :laughing:

**Comment by linsui** [comment]
This pr is ready for review.

**Comment by 6543** [comment]
big thanks to @linsui :) !!!

**Comment by Gedsh** [comment]
> This pr is ready for review. Here is the apk for test. Thanks!

Thank you for the great job!

**Pull request merged**
